name: Database Update

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
      - cron: '0 */2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
    - name: Build
      run: dotnet build
    - name: Update
      run: dotnet run --project DatabaseUpdater "$env:GH_PAT"
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
